### PR TITLE
Update release_0_1_0.php

### PR DESCRIPTION
**Pull request by dmzx**

### CODE REVIEW

**Comment by Galixte** [comment]
Hi @bruninoit,

have you see that ?

**Comment by bruninoit** [comment]
There is just this code...

**Comment by Galixte** [comment]
Hi,

ok but this code from @dmzx is to remove all additionals datas from the database when the user deletes data.

Currently, does your extension removes data from database after delete data action ?

**Comment by bruninoit** [comment]
Yes

**Comment by Galixte** [comment]
Ok thanks, i think this issue can be closed now ? @dmzx

**Pull request closed without merging**
